#service name
spring:
  application:
    name: school-service    

#port number    
server:
  port: 9098    
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
 
logging:
  level:
    com.example.howtodoinjava: DEBUG