spring:
    application:
        name: discovery-service
    cloud:
        config:
            uri: http://localhost:8888
            
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false